# Generated by Django 5.0.6 on 2024-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailySleep', '0002_alter_dailysleep_end_alter_dailysleep_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysleep',
            name='userAddS',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
