# Generated by Django 5.0 on 2023-12-08 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyDream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydream',
            name='dreamDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
