# Generated by Django 5.0.6 on 2024-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyDream', '0002_dailydream_dreamdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydream',
            name='userNameAddS',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
